CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS customers_created_at_idx ON customers (created_at DESC);
CREATE INDEX IF NOT EXISTS customers_name_idx ON customers USING GIN (to_tsvector('simple', name));

DROP TRIGGER IF EXISTS customers_set_updated_at ON customers;
CREATE TRIGGER customers_set_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS sms_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_body TEXT NOT NULL,
  send_type TEXT NOT NULL DEFAULT 'immediate' CHECK (send_type IN ('immediate', 'scheduled', 'test')),
  recipient_type TEXT NOT NULL DEFAULT 'all' CHECK (recipient_type IN ('all', 'single', 'selected', 'test')),
  recipient_customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'scheduled', 'failed', 'cancelled')),
  total_recipients INTEGER NOT NULL DEFAULT 0,
  valid_recipients INTEGER NOT NULL DEFAULT 0,
  invalid_recipients INTEGER NOT NULL DEFAULT 0,
  scheduled_at TIMESTAMPTZ NULL,
  sent_at TIMESTAMPTZ NULL,
  provider TEXT NOT NULL DEFAULT 'UGSMS',
  provider_response TEXT NULL,
  error_message TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sms_messages_created_at_idx ON sms_messages (created_at DESC);
CREATE INDEX IF NOT EXISTS sms_messages_scheduled_idx ON sms_messages (scheduled_at) WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS sms_messages_status_idx ON sms_messages (status);

CREATE TABLE IF NOT EXISTS sms_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sms_message_id BIGINT NOT NULL REFERENCES sms_messages(id) ON DELETE CASCADE,
  customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
  phone_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('sent', 'scheduled', 'failed', 'cancelled')),
  error_message TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sms_recipients_message_idx ON sms_recipients (sms_message_id);
CREATE INDEX IF NOT EXISTS sms_recipients_customer_idx ON sms_recipients (customer_id);

CREATE TABLE IF NOT EXISTS sms_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general' CHECK (category IN ('maintenance', 'offer', 'service', 'payment', 'general')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sms_templates_created_at_idx ON sms_templates (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS sms_templates_title_idx ON sms_templates (title);

DROP TRIGGER IF EXISTS sms_templates_set_updated_at ON sms_templates;
CREATE TRIGGER sms_templates_set_updated_at
BEFORE UPDATE ON sms_templates
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO sms_templates (title, category, message)
VALUES
  (
    'Maintenance Notice',
    'maintenance',
    'Dear customer, our Wi-Fi service will be under maintenance on [DATE] from [START_TIME] to [END_TIME]. Please plan ahead. Thank you.'
  ),
  (
    'Service Restored',
    'service',
    'Dear customer, Omega Wi-Fi service has been restored. Thank you for your patience.'
  ),
  (
    'Weekend Offer',
    'offer',
    'Dear customer, enjoy our weekend Wi-Fi offer. Get [OFFER_DETAILS]. Valid until [DATE].'
  ),
  (
    'Payment Reminder',
    'payment',
    'Dear customer, your Wi-Fi package is about to expire. Please renew to continue enjoying Omega Wi-Fi.'
  ),
  (
    'General Announcement',
    'general',
    'Dear customer, we have an important update from Omega Wi-Fi: [MESSAGE]'
  )
ON CONFLICT (title) DO NOTHING;
